SELECT d.DNAME, e.SAL, e.ENAME,
       ROUND(avg(SAL) OVER (PARTITION BY d.DNAME), 2) AS AVG_BY_DEPTNO,
       MAX(SAL) OVER (PARTITION BY DNAME) AS MAX_BY_DEPTNO
FROM SCOTT.EMP e
    JOIN SCOTT.DEPT d ON e.DEPTNO = d.DEPTNO
group by e.ENAME, e.SAL, d.DNAME
ORDER BY AVG_BY_DEPTNO DESC, MAX_BY_DEPTNO DESC;
